# Generated by Django 3.2 on 2021-06-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='line_item_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
