# Generated by Django 3.2 on 2021-06-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_lineitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
