# Generated by Django 3.2 on 2021-06-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitem',
            name='images',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
