# Generated by Django 3.2 on 2021-04-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_url', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'tbl_shopify_store',
            },
        ),
    ]
